
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: 
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=postgres://postgres:admin@localhost:5433/ged_db

    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5001
    depends_on:
      - backend

volumes:
  pgdata:
